// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABLooXb7iy65gDukG600fFDZjXM1xv_DE',
    appId: '1:1005041529553:web:e25fcd2b0aa403f6448bf0',
    messagingSenderId: '1005041529553',
    projectId: 'absensi-app-dcbcd',
    authDomain: 'absensi-app-dcbcd.firebaseapp.com',
    storageBucket: 'absensi-app-dcbcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQjrF-sLor0NdhfEielbf910JeGskRS4U',
    appId: '1:1005041529553:android:c50b66a9d00a5707448bf0',
    messagingSenderId: '1005041529553',
    projectId: 'absensi-app-dcbcd',
    storageBucket: 'absensi-app-dcbcd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABLooXb7iy65gDukG600fFDZjXM1xv_DE',
    appId: '1:1005041529553:web:6a2375084975dc9c448bf0',
    messagingSenderId: '1005041529553',
    projectId: 'absensi-app-dcbcd',
    authDomain: 'absensi-app-dcbcd.firebaseapp.com',
    storageBucket: 'absensi-app-dcbcd.firebasestorage.app',
  );

}